// source: debonding_delegation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.debondingdelegation.DebondingDelegation', null, global);
goog.exportSymbol('proto.debondingdelegation.DebondingDelegationEntry', null, global);
goog.exportSymbol('proto.debondingdelegation.DebondingDelegationInnerEntry', null, global);
goog.exportSymbol('proto.debondingdelegation.GetByAddressRequest', null, global);
goog.exportSymbol('proto.debondingdelegation.GetByAddressResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.debondingdelegation.DebondingDelegationEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.debondingdelegation.DebondingDelegationEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.debondingdelegation.DebondingDelegationEntry.displayName = 'proto.debondingdelegation.DebondingDelegationEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.debondingdelegation.DebondingDelegationInnerEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.debondingdelegation.DebondingDelegationInnerEntry.repeatedFields_, null);
};
goog.inherits(proto.debondingdelegation.DebondingDelegationInnerEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.debondingdelegation.DebondingDelegationInnerEntry.displayName = 'proto.debondingdelegation.DebondingDelegationInnerEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.debondingdelegation.DebondingDelegation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.debondingdelegation.DebondingDelegation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.debondingdelegation.DebondingDelegation.displayName = 'proto.debondingdelegation.DebondingDelegation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.debondingdelegation.GetByAddressRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.debondingdelegation.GetByAddressRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.debondingdelegation.GetByAddressRequest.displayName = 'proto.debondingdelegation.GetByAddressRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.debondingdelegation.GetByAddressResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.debondingdelegation.GetByAddressResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.debondingdelegation.GetByAddressResponse.displayName = 'proto.debondingdelegation.GetByAddressResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.debondingdelegation.DebondingDelegationEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.debondingdelegation.DebondingDelegationEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.debondingdelegation.DebondingDelegationEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.debondingdelegation.DebondingDelegationEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    entriesMap: (f = msg.getEntriesMap()) ? f.toObject(includeInstance, proto.debondingdelegation.DebondingDelegationInnerEntry.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.debondingdelegation.DebondingDelegationEntry}
 */
proto.debondingdelegation.DebondingDelegationEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.debondingdelegation.DebondingDelegationEntry;
  return proto.debondingdelegation.DebondingDelegationEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.debondingdelegation.DebondingDelegationEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.debondingdelegation.DebondingDelegationEntry}
 */
proto.debondingdelegation.DebondingDelegationEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getEntriesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.debondingdelegation.DebondingDelegationInnerEntry.deserializeBinaryFromReader, "", new proto.debondingdelegation.DebondingDelegationInnerEntry());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.debondingdelegation.DebondingDelegationEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.debondingdelegation.DebondingDelegationEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.debondingdelegation.DebondingDelegationEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.debondingdelegation.DebondingDelegationEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntriesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.debondingdelegation.DebondingDelegationInnerEntry.serializeBinaryToWriter);
  }
};


/**
 * map<string, DebondingDelegationInnerEntry> entries = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.debondingdelegation.DebondingDelegationInnerEntry>}
 */
proto.debondingdelegation.DebondingDelegationEntry.prototype.getEntriesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.debondingdelegation.DebondingDelegationInnerEntry>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.debondingdelegation.DebondingDelegationInnerEntry));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.debondingdelegation.DebondingDelegationEntry} returns this
 */
proto.debondingdelegation.DebondingDelegationEntry.prototype.clearEntriesMap = function() {
  this.getEntriesMap().clear();
  return this;};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.debondingdelegation.DebondingDelegationInnerEntry.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.debondingdelegation.DebondingDelegationInnerEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.debondingdelegation.DebondingDelegationInnerEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.debondingdelegation.DebondingDelegationInnerEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.debondingdelegation.DebondingDelegationInnerEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    debondingdelegationsList: jspb.Message.toObjectList(msg.getDebondingdelegationsList(),
    proto.debondingdelegation.DebondingDelegation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.debondingdelegation.DebondingDelegationInnerEntry}
 */
proto.debondingdelegation.DebondingDelegationInnerEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.debondingdelegation.DebondingDelegationInnerEntry;
  return proto.debondingdelegation.DebondingDelegationInnerEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.debondingdelegation.DebondingDelegationInnerEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.debondingdelegation.DebondingDelegationInnerEntry}
 */
proto.debondingdelegation.DebondingDelegationInnerEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.debondingdelegation.DebondingDelegation;
      reader.readMessage(value,proto.debondingdelegation.DebondingDelegation.deserializeBinaryFromReader);
      msg.addDebondingdelegations(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.debondingdelegation.DebondingDelegationInnerEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.debondingdelegation.DebondingDelegationInnerEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.debondingdelegation.DebondingDelegationInnerEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.debondingdelegation.DebondingDelegationInnerEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDebondingdelegationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.debondingdelegation.DebondingDelegation.serializeBinaryToWriter
    );
  }
};


/**
 * repeated DebondingDelegation debondingDelegations = 1;
 * @return {!Array<!proto.debondingdelegation.DebondingDelegation>}
 */
proto.debondingdelegation.DebondingDelegationInnerEntry.prototype.getDebondingdelegationsList = function() {
  return /** @type{!Array<!proto.debondingdelegation.DebondingDelegation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.debondingdelegation.DebondingDelegation, 1));
};


/**
 * @param {!Array<!proto.debondingdelegation.DebondingDelegation>} value
 * @return {!proto.debondingdelegation.DebondingDelegationInnerEntry} returns this
*/
proto.debondingdelegation.DebondingDelegationInnerEntry.prototype.setDebondingdelegationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.debondingdelegation.DebondingDelegation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.debondingdelegation.DebondingDelegation}
 */
proto.debondingdelegation.DebondingDelegationInnerEntry.prototype.addDebondingdelegations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.debondingdelegation.DebondingDelegation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.debondingdelegation.DebondingDelegationInnerEntry} returns this
 */
proto.debondingdelegation.DebondingDelegationInnerEntry.prototype.clearDebondingdelegationsList = function() {
  return this.setDebondingdelegationsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.debondingdelegation.DebondingDelegation.prototype.toObject = function(opt_includeInstance) {
  return proto.debondingdelegation.DebondingDelegation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.debondingdelegation.DebondingDelegation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.debondingdelegation.DebondingDelegation.toObject = function(includeInstance, msg) {
  var f, obj = {
    shares: msg.getShares_asB64(),
    debondendtime: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.debondingdelegation.DebondingDelegation}
 */
proto.debondingdelegation.DebondingDelegation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.debondingdelegation.DebondingDelegation;
  return proto.debondingdelegation.DebondingDelegation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.debondingdelegation.DebondingDelegation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.debondingdelegation.DebondingDelegation}
 */
proto.debondingdelegation.DebondingDelegation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setShares(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDebondendtime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.debondingdelegation.DebondingDelegation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.debondingdelegation.DebondingDelegation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.debondingdelegation.DebondingDelegation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.debondingdelegation.DebondingDelegation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShares_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getDebondendtime();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
};


/**
 * optional bytes shares = 1;
 * @return {!(string|Uint8Array)}
 */
proto.debondingdelegation.DebondingDelegation.prototype.getShares = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes shares = 1;
 * This is a type-conversion wrapper around `getShares()`
 * @return {string}
 */
proto.debondingdelegation.DebondingDelegation.prototype.getShares_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getShares()));
};


/**
 * optional bytes shares = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getShares()`
 * @return {!Uint8Array}
 */
proto.debondingdelegation.DebondingDelegation.prototype.getShares_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getShares()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.debondingdelegation.DebondingDelegation} returns this
 */
proto.debondingdelegation.DebondingDelegation.prototype.setShares = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional uint64 DebondEndTime = 2;
 * @return {number}
 */
proto.debondingdelegation.DebondingDelegation.prototype.getDebondendtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.debondingdelegation.DebondingDelegation} returns this
 */
proto.debondingdelegation.DebondingDelegation.prototype.setDebondendtime = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.debondingdelegation.GetByAddressRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.debondingdelegation.GetByAddressRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.debondingdelegation.GetByAddressRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.debondingdelegation.GetByAddressRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: jspb.Message.getFieldWithDefault(msg, 1, ""),
    height: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.debondingdelegation.GetByAddressRequest}
 */
proto.debondingdelegation.GetByAddressRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.debondingdelegation.GetByAddressRequest;
  return proto.debondingdelegation.GetByAddressRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.debondingdelegation.GetByAddressRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.debondingdelegation.GetByAddressRequest}
 */
proto.debondingdelegation.GetByAddressRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setHeight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.debondingdelegation.GetByAddressRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.debondingdelegation.GetByAddressRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.debondingdelegation.GetByAddressRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.debondingdelegation.GetByAddressRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional string address = 1;
 * @return {string}
 */
proto.debondingdelegation.GetByAddressRequest.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.debondingdelegation.GetByAddressRequest} returns this
 */
proto.debondingdelegation.GetByAddressRequest.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 height = 2;
 * @return {number}
 */
proto.debondingdelegation.GetByAddressRequest.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.debondingdelegation.GetByAddressRequest} returns this
 */
proto.debondingdelegation.GetByAddressRequest.prototype.setHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.debondingdelegation.GetByAddressResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.debondingdelegation.GetByAddressResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.debondingdelegation.GetByAddressResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.debondingdelegation.GetByAddressResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    debondingDelegationsMap: (f = msg.getDebondingDelegationsMap()) ? f.toObject(includeInstance, proto.debondingdelegation.DebondingDelegationInnerEntry.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.debondingdelegation.GetByAddressResponse}
 */
proto.debondingdelegation.GetByAddressResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.debondingdelegation.GetByAddressResponse;
  return proto.debondingdelegation.GetByAddressResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.debondingdelegation.GetByAddressResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.debondingdelegation.GetByAddressResponse}
 */
proto.debondingdelegation.GetByAddressResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getDebondingDelegationsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.debondingdelegation.DebondingDelegationInnerEntry.deserializeBinaryFromReader, "", new proto.debondingdelegation.DebondingDelegationInnerEntry());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.debondingdelegation.GetByAddressResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.debondingdelegation.GetByAddressResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.debondingdelegation.GetByAddressResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.debondingdelegation.GetByAddressResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDebondingDelegationsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.debondingdelegation.DebondingDelegationInnerEntry.serializeBinaryToWriter);
  }
};


/**
 * map<string, DebondingDelegationInnerEntry> debonding_delegations = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.debondingdelegation.DebondingDelegationInnerEntry>}
 */
proto.debondingdelegation.GetByAddressResponse.prototype.getDebondingDelegationsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.debondingdelegation.DebondingDelegationInnerEntry>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.debondingdelegation.DebondingDelegationInnerEntry));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.debondingdelegation.GetByAddressResponse} returns this
 */
proto.debondingdelegation.GetByAddressResponse.prototype.clearDebondingDelegationsMap = function() {
  this.getDebondingDelegationsMap().clear();
  return this;};


goog.object.extend(exports, proto.debondingdelegation);
